### PR TITLE
Idea how to implement more than one connection..

### PR DESCRIPTION
**Pull request by aleswita**
Please, check diff, if my solution of more connections are acceptable, tnx.

### CODE REVIEW

**Comment by f3l1x** [comment]
It looks good as prototype. I would go to more clear way.

```yaml
dbal:
  connections:
    defaualt: # would be required
      ....
    foo: # optional
      ....
    bar: # optional
      ...
```

Using this schema, you get rid of handling default/non-default.

**Comment by f3l1x** [comment]
Have you considered providing default/non-default connections into command and other parts of doctrine?

**Comment by aleswita** [comment]
commit ce5fb5e
- change default configuration 'connection' => 'connections'
- require 'default' connection

@f3l1x so next step i think is change **Nettrine\ORM\DI\OrmExtension** to provide one **EntityManger** per connection

**Comment by f3l1x** [comment]
Agree. Could you please create same PR for nettrine/orm? And for more, could you please create example to playground? This is to BC change and we need to be sure. Type name of this branch directly in composer.json in playground.

Thank you very much.

**Comment by aleswita** [comment]
commit 987f955
- its for use connectionstring in oci8 driver

```neon
dbal:
	connections:
		mis:
			connectstring: "(...)"
			driver: oci8
			...

**Comment by f3l1x** [comment]
Could you please send me generated containers? Do you know what kind of caching Kdyby use by default? 

It is really cool you did this benchmark. Its so important.

**Comment by f3l1x** [comment]
We should also think about connections in console commands and tracy panel. Any idea?

**Comment by aleswita** [comment]
For tracy panel a think its easy, iterate on config connections.

For console commads probably use same solution like in ORM PR: https://github.com/nettrine/orm/pull/17/files#diff-ca75d2795a0bc290b753eaa27d3c1a9bR145

**Comment by aleswita** [comment]
Continue here: https://github.com/nettrine/dbal/pull/24

**Pull request closed without merging**
